# Generated by Django 6.0.5 on 2026-05-17 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_loja', '0003_produto_estoque_produto_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='venda',
            name='metodo_pagamento',
            field=models.CharField(choices=[('PIX', 'PIX'), ('DINHEIRO', 'Dinheiro'), ('CREDITO', 'Cartão de Crédito'), ('DEBITO', 'Cartão de Débito')], default='PIX', max_length=20),
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_loja.produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core_loja.venda')),
            ],
        ),
    ]
